"""empty message

Revision ID: 9c3d7c779a05
Revises: 
Create Date: 2024-12-05 05:10:21.813858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3d7c779a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtm_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_child_col', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtm_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_parent_col', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_as',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_a', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_bs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_b', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('child_as',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_a', sa.String(length=100), nullable=False),
    sa.Column('parent_a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_a_id'], ['parent_as.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_bs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_b', sa.String(length=100), nullable=False),
    sa.Column('parent_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_b_id'], ['parent_bs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtm_parent_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtm_extra_data', sa.String(length=150), nullable=False),
    sa.Column('mtm_parent_join_id', sa.Integer(), nullable=True),
    sa.Column('mtm_child_join_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mtm_child_join_id'], ['mtm_children.id'], ),
    sa.ForeignKeyConstraint(['mtm_parent_join_id'], ['mtm_parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtm_parent_children')
    op.drop_table('child_bs')
    op.drop_table('child_as')
    op.drop_table('users')
    op.drop_table('parent_bs')
    op.drop_table('parent_as')
    op.drop_table('mtm_parents')
    op.drop_table('mtm_children')
    # ### end Alembic commands ###
